from fastapi import APIRouter, Depends, HTTPException, status

from schemas import (
    CameraAddRequest,
    CameraUpdateRequest,
    CameraStatusResponse,
)
from core.camera_manager import CameraManager
from api.deps import get_camera_manager

router = APIRouter(prefix="/cameras", tags=["Cameras"])


@router.get(
    "",
    response_model=list[CameraStatusResponse],
    summary="List all cameras",
    description=(
        "Returns all cameras with current status and statistics.\n\n"
        "**Statuses:**\n"
        "- `running` — connected, capturing frames\n"
        "- `connecting` — attempting to connect\n"
        "- `stopped` — stopped manually\n"
        "- `error` — connection lost, waiting for reconnect"
    ),
)
async def list_cameras(
    manager: CameraManager = Depends(get_camera_manager),
) -> list[CameraStatusResponse]:
    return manager.get_all()


@router.get(
    "/{camera_id}",
    response_model=CameraStatusResponse,
    summary="Get status of a specific camera",
    description=(
        "Returns detailed information about a camera, its current status "
        "(running/stopped/error), and frame processing statistics."
    ),
    responses={404: {"description": "Camera with this ID not found"}},
)
async def get_camera(
    camera_id: int,
    manager: CameraManager = Depends(get_camera_manager),
) -> CameraStatusResponse:
    try:
        return manager.get_one(camera_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc))


@router.post(
    "",
    response_model=CameraStatusResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Add a camera",
    description=(
        "Adds a new camera to the system. The ID is auto-generated by the database.\n\n"
        "### Parameter Recommendations:\n"
        "- **FPS**: 1.0–5.0 is enough for motion detection. More creates unnecessary load.\n"
        "- **Resize Width**: 1280 (720p) — ideal balance for neural networks.\n"
        "- **JPEG Quality**: 85 — preserves detail and saves traffic.\n\n"
        "### Example\n"
        "```json\n"
        '{ "rtsp": "rtsp://192.168.1.100:554/stream", "name": "Entrance" }\n'
        "```"
    ),
)
async def add_camera(
    body: CameraAddRequest,
    manager: CameraManager = Depends(get_camera_manager),
) -> CameraStatusResponse:
    try:
        return manager.add_camera(body)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.patch(
    "/{camera_id}",
    response_model=CameraStatusResponse,
    summary="Update camera parameters",
    description=(
        "Partial settings update. You can change FPS, name, stream, etc.\n\n"
        "**Note:** if you change `rtsp`, the camera will need to be "
        "restarted (`/stop`, then `/start`) for the connection to update."
    ),
    responses={404: {"description": "Camera not found"}},
)
async def update_camera(
    camera_id: int,
    body: CameraUpdateRequest,
    manager: CameraManager = Depends(get_camera_manager),
) -> CameraStatusResponse:
    try:
        return manager.update_camera(camera_id, body)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc))


@router.delete(
    "/{camera_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete camera",
    responses={404: {"description": "Camera not found"}},
)
async def remove_camera(
    camera_id: int,
    manager: CameraManager = Depends(get_camera_manager),
) -> None:
    try:
        await manager.remove_camera(camera_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc))


@router.post(
    "/{camera_id}/start",
    response_model=CameraStatusResponse,
    summary="Start camera",
    responses={404: {"description": "Camera not found"}},
)
async def start_camera(
    camera_id: int,
    manager: CameraManager = Depends(get_camera_manager),
) -> CameraStatusResponse:
    try:
        return manager.start_camera(camera_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc))


@router.post(
    "/{camera_id}/stop",
    response_model=CameraStatusResponse,
    summary="Stop camera",
    responses={404: {"description": "Camera not found"}},
)
async def stop_camera(
    camera_id: int,
    manager: CameraManager = Depends(get_camera_manager),
) -> CameraStatusResponse:
    try:
        return await manager.stop_camera(camera_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
