from typing import Protocol, List

from schemas import CameraConfig


class ICameraRepository(Protocol):
    """Protocol for persisting camera configurations."""

    def load_all(self) -> List[CameraConfig]: ...
    def save_all(self, cameras: List[CameraConfig]) -> None: ...
    def add(self, camera: CameraConfig) -> int: ...
    def update(self, camera: CameraConfig) -> None: ...
    def delete(self, camera_id: int) -> None: ...
